version: '3'

services:
  app:
    container_name: homebroker
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - my-network

  db:
    container_name: homebroker_db
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest
    networks:
      - my-network

volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    external: true


# //Linux ou Mac
# /etc/hosts

# 127.0.0.1 host.docker.internal

# //Windows
# C:\Windows\system32\drivers\etc\hosts (bloco de notas como administrador)
# 127.0.0.1 host.docker.internal