version: "3"

services:
  api:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: codebank-nestjs
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    build: .docker/postgres
    container_name: codebank-nestjs-db
    tty: true
    ports:
      - 5433:5432
    volumes: 
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: codebank-nestjs-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80